app: bondstreet
ssh_url: bondstreet@deploy.eu2.frbit.com
ssh_path: null
git_remote: bondstreet/master
before:
    code/up:
        - 'echo  "Script example: " $(git rev-parse HEAD)'
after:
    code/down:
        - 'php craft migrate/all'
